/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

/**
 *
 * @author user
 */
public class AddFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form AddFuncionario
     */
    public AddFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnovofuncionario = new javax.swing.JPanel();
        jlcodigofunc = new javax.swing.JLabel();
        jlnomefunc = new javax.swing.JLabel();
        jlenderecofunc = new javax.swing.JLabel();
        jltelfunc = new javax.swing.JLabel();
        jlsalariofunc = new javax.swing.JLabel();
        jbcancelarfunc = new javax.swing.JButton();
        CodigoF = new javax.swing.JTextField();
        NomeF = new javax.swing.JTextField();
        EnderecoF = new javax.swing.JTextField();
        TelF = new javax.swing.JTextField();
        jbsalvarfunc = new javax.swing.JButton();
        Salario = new javax.swing.JTextField();
        jlnumfunc = new javax.swing.JLabel();
        NF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Funcionários");
        setResizable(false);

        jlcodigofunc.setText("Codigo:");

        jlnomefunc.setText("Nome:");

        jlenderecofunc.setText("Endereço:");

        jltelfunc.setText("Tel:");

        jlsalariofunc.setText("Salario:");

        jbcancelarfunc.setText("Limpar");
        jbcancelarfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarfuncActionPerformed(evt);
            }
        });

        CodigoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoFActionPerformed(evt);
            }
        });

        jbsalvarfunc.setText("Salvar");
        jbsalvarfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarfuncActionPerformed(evt);
            }
        });

        jlnumfunc.setText("Nº");

        jButton1.setText("Excluir");

        javax.swing.GroupLayout jpnovofuncionarioLayout = new javax.swing.GroupLayout(jpnovofuncionario);
        jpnovofuncionario.setLayout(jpnovofuncionarioLayout);
        jpnovofuncionarioLayout.setHorizontalGroup(
            jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jltelfunc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlsalariofunc, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jlenderecofunc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlnomefunc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlcodigofunc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                        .addComponent(EnderecoF, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jlnumfunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                        .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jbsalvarfunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbcancelarfunc))
                            .addComponent(TelF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpnovofuncionarioLayout.setVerticalGroup(
            jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnovofuncionarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcodigofunc))
                .addGap(18, 18, 18)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnomefunc))
                .addGap(18, 18, 18)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlenderecofunc)
                    .addComponent(NF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnumfunc))
                .addGap(18, 18, 18)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelF, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jltelfunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlsalariofunc))
                .addGap(18, 18, 18)
                .addGroup(jpnovofuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsalvarfunc)
                    .addComponent(jbcancelarfunc)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnovofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnovofuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbcancelarfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarfuncActionPerformed
        CodigoF.setText("");
        NomeF.setText("");
        EnderecoF.setText("");
        NF.setText("");
        TelF.setText("");
        Salario.setText("");            
        
    }//GEN-LAST:event_jbcancelarfuncActionPerformed

    private void jbsalvarfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarfuncActionPerformed
        
    }//GEN-LAST:event_jbsalvarfuncActionPerformed

    private void CodigoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddFuncionario dialog = new AddFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoF;
    private javax.swing.JTextField EnderecoF;
    private javax.swing.JTextField NF;
    private javax.swing.JTextField NomeF;
    private javax.swing.JTextField Salario;
    private javax.swing.JTextField TelF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbcancelarfunc;
    private javax.swing.JButton jbsalvarfunc;
    private javax.swing.JLabel jlcodigofunc;
    private javax.swing.JLabel jlenderecofunc;
    private javax.swing.JLabel jlnomefunc;
    private javax.swing.JLabel jlnumfunc;
    private javax.swing.JLabel jlsalariofunc;
    private javax.swing.JLabel jltelfunc;
    private javax.swing.JPanel jpnovofuncionario;
    // End of variables declaration//GEN-END:variables
}
